CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT UNIQUE NOT NULL,
  EMAIL TEXT,
  PASS_HASH TEXT NOT NULL,
  ACTIVE INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ROLES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
  USER_ID INT NOT NULL,
  ROLE_ID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PASSWORD_RESET (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID INTEGER NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
  TOKEN TEXT NOT NULL UNIQUE,
  EXPIRA TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_password_reset_user ON PASSWORD_RESET(USER_ID);
CREATE INDEX IF NOT EXISTS idx_password_reset_token ON PASSWORD_RESET(TOKEN);

CREATE TABLE IF NOT EXISTS ESTACION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE TEXT UNIQUE NOT NULL,
  ENCARGADO TEXT NOT NULL,
  GEOUBICACION TEXT,
  TIPO_PEZ TEXT,
  LITROS_APROX REAL,
  PECES_APROX INTEGER,
  FECHA_INICIO TEXT,
  CANTIDAD_TANQUES INTEGER,
  ALTITUD INTEGER,
  AREA_M2 REAL,
  FUENTE_AGUA TEXT
);

CREATE TABLE IF NOT EXISTS TANQUE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ESTACION_ID INT NOT NULL,
  CODIGO TEXT NOT NULL,
  CAPACIDAD_L REAL NOT NULL,
  TIPO_PEZ TEXT,
  PECES_APROX INTEGER,
  FECHA_INICIO TEXT,
  UNIQUE(ESTACION_ID, CODIGO),
  FOREIGN KEY (ESTACION_ID) REFERENCES ESTACION(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LOTE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE TEXT NOT NULL,
  ESTADO TEXT NOT NULL,
  DEPARTAMENTO TEXT,
  MUNICIPIO TEXT
);

CREATE TABLE IF NOT EXISTS MUESTREO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LOTE_ID INT NOT NULL,
  ESTACION_ID INT NOT NULL,
  TANQUE_ID INT NOT NULL,
  FECHA_HORA TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FOTO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  MUESTREO_ID INT,
  ESTACION_ID INT,
  TANQUE_ID INT,
  PARTE TEXT NOT NULL,
  RUTA TEXT NOT NULL,
  QC_OK INTEGER NOT NULL,
  ESTADO TEXT NOT NULL,
  LABEL TEXT,
  PROB REAL,
  MENSAJE_ERROR TEXT,
  FOREIGN KEY (ESTACION_ID) REFERENCES ESTACION(ID) ON DELETE CASCADE,
  FOREIGN KEY (TANQUE_ID) REFERENCES TANQUE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BITACORA (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT,
  ACCION TEXT,
  ENTIDAD TEXT,
  ENTIDAD_ID INT,
  FECHA_HORA TEXT NOT NULL,
  DETALLE TEXT
);

-- Historial de limpiezas por tanque
CREATE TABLE IF NOT EXISTS TANQUE_LIMPIEZA (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  tanque_id   INTEGER NOT NULL,
  fecha       TEXT    NOT NULL,              -- ISO yyyy-MM-dd
  responsable TEXT    NOT NULL,
  descripcion TEXT    NOT NULL,
  created_at  TEXT    DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tanque_id) REFERENCES TANQUE(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_limpieza_tanque_fecha
  ON TANQUE_LIMPIEZA(tanque_id, fecha);

-- =========================================
--  LIMPIEZAS POR TANQUE
-- =========================================
CREATE TABLE IF NOT EXISTS TANQUE_LIMPIEZA (
  ID           INTEGER PRIMARY KEY AUTOINCREMENT,
  TANQUE_ID    INTEGER NOT NULL,
  FECHA        TEXT    NOT NULL,              -- ISO yyyy-MM-dd
  RESPONSABLE  TEXT,
  DESCRIPCION  TEXT,
  FOREIGN KEY (TANQUE_ID) REFERENCES TANQUE(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_LIMPIEZA_TANQUE  ON TANQUE_LIMPIEZA (TANQUE_ID);
CREATE INDEX IF NOT EXISTS IX_LIMPIEZA_FECHA   ON TANQUE_LIMPIEZA (FECHA);


PRAGMA foreign_keys = ON;

-- ===== BASE (ya la tienes, se deja por si acaso) =====

CREATE TABLE IF NOT EXISTS ESTACION (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE      TEXT NOT NULL UNIQUE,
    UBICACION   TEXT
);

CREATE TABLE IF NOT EXISTS TANQUE (
    ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    ESTACION_ID  INTEGER NOT NULL REFERENCES ESTACION(ID) ON DELETE CASCADE,
    NOMBRE       TEXT NOT NULL,
    VOLUMEN_L    REAL,
    OBS          TEXT,
    UNIQUE (ESTACION_ID, NOMBRE)
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME  TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USERS (
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME   TEXT NOT NULL UNIQUE,
    EMAIL      TEXT,
    PASS_HASH  TEXT NOT NULL,
    ACTIVE     INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID  INTEGER NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    ROLE_ID  INTEGER NOT NULL REFERENCES ROLES(ID) ON DELETE CASCADE,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

-- ===== NUEVA: HISTORIAL DE LIMPIEZAS POR TANQUE =====
CREATE TABLE IF NOT EXISTS TANQUE_LIMPIEZA (
    ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    TANQUE_ID    INTEGER NOT NULL REFERENCES TANQUE(ID) ON DELETE CASCADE,
    FECHA        TEXT    NOT NULL,        -- ISO-8601 (yyyy-MM-dd)
    RESPONSABLE  TEXT,
    DESCRIPCION  TEXT
);

-- índices útiles
CREATE INDEX IF NOT EXISTS IDX_LIMPIEZA_TANQUE ON TANQUE_LIMPIEZA(TANQUE_ID, FECHA);
