CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT UNIQUE NOT NULL,
  PASS_HASH TEXT NOT NULL,
  ACTIVE INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ROLES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
  USER_ID INT NOT NULL,
  ROLE_ID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ESTACION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS TANQUE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ESTACION_ID INT NOT NULL,
  CODIGO TEXT NOT NULL,
  CAPACIDAD_L REAL NOT NULL,
  UNIQUE(ESTACION_ID, CODIGO)
);

CREATE TABLE IF NOT EXISTS LOTE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE TEXT NOT NULL,
  ESTADO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MUESTREO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LOTE_ID INT NOT NULL,
  ESTACION_ID INT NOT NULL,
  TANQUE_ID INT NOT NULL,
  FECHA_HORA TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FOTO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  MUESTREO_ID INT NOT NULL,
  PARTE TEXT NOT NULL,
  RUTA TEXT NOT NULL,
  QC_OK INTEGER NOT NULL,
  ESTADO TEXT NOT NULL,
  LABEL TEXT,
  PROB REAL,
  MENSAJE_ERROR TEXT
);

CREATE TABLE IF NOT EXISTS BITACORA (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT,
  ACCION TEXT,
  ENTIDAD TEXT,
  ENTIDAD_ID INT,
  FECHA_HORA TEXT NOT NULL,
  DETALLE TEXT
);
